rss:
  - https://aws.amazon.com/blogs/aws/feed/
  - https://aws.amazon.com/new/feed/

html:
  - url: https://boards.greenhouse.io/stripe
    item: "div.opening, .opening"
    title: "a"
    link: "a"
    date: ""
    date_fmt: ""
    timeout: 20

  - url: https://boards.greenhouse.io/databricks
    item: "div.opening, .opening"
    title: "a"
    link: "a"
    date: ""
    date_fmt: ""
    timeout: 20

  - url: https://boards.greenhouse.io/notion
    item: "div.opening, .opening"
    title: "a"
    link: "a"
    date: ""
    date_fmt: ""
    timeout: 20

  - url: https://boards.greenhouse.io/cloudflare
    item: "div.opening, .opening"
    title: "a"
    link: "a"
    date: ""
    date_fmt: ""
    timeout: 20

  - url: https://boards.greenhouse.io/github
    item: "div.opening, .opening"
    title: "a"
    link: "a"
    date: ""
    date_fmt: ""
    timeout: 20

settings:
  freshness_days: 90
  verify_http_200: true
