rss:
  - https://aws.amazon.com/blogs/aws/feed/
  - https://aws.amazon.com/new/feed/
  - https://status.aws.amazon.com/rss/all.rss

html:
  - url: https://developers.google.com/events
    item: "article"           
    title: "h3, h2"
    link: "a"
    include: "/events/"       
    date: ""
    date_fmt: ""

  - url: https://developer.microsoft.com/en-us/reactor/
    item: "article"          
    title: "h3, h2, a"
    link: "a"
    include: "/reactor/events/"
    date: ""
    date_fmt: ""

settings:
  freshness_days: 90
  verify_http_200: true

