rss:
  - https://boards-api.greenhouse.io/v1/boards/figma/jobs?content=true    
  - https://community.aws/events/rss                                    
  - https://about.google/events/feed/                                    
  - https://developer.microsoft.com/reactor/feed/                        

html:

  - url: https://boards.greenhouse.io/figma
    item: "div.opening"          
    title: "a"
    link: "a"
    date: ""                     
    date_fmt: ""

  - url: https://careers.roblox.com/jobs
    item: "li.jobs-list-item"
    title: "h3"
    link: "a"
    date: "time"
    date_fmt: ""                

settings:
  freshness_days: 90
  verify_http_200: true
