name: Scrape & Publish

on:
  workflow_dispatch:
  schedule:
    - cron: "17 9 * * *"  

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyyaml
      - run: |
          python -c "import sys; sys.path.append(''); from scripts.run_all import run; run()"
      - name: Commit data & docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data docs
          git commit -m "auto: update jobs + pages" || echo "No changes"
          git push
