name: Update Hiring Events

on:
  schedule:
    - cron: "0 12 * * *"   # daily at 12:00 UTC (8am ET)
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - "scripts/**"
      - "data/**"
      - "requirements.txt"
      - ".github/workflows/update-events.yml"
      - "README.md"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updater
        env:
          SEARCH_TERMS: ${{ secrets.SEARCH_TERMS }}
          LOCATIONS: ${{ secrets.LOCATIONS }}
        run: |
          python scripts/update_events.py

      - name: Mirror README to index.md for GitHub Pages
        run: |
          cp README.md index.md
          touch .nojekyll   # ensures GitHub Pages doesn’t try to build with Jekyll

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore: auto-update events $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit."
          fi
